"""Numerical regression test for the RTMt.sb (Stefan-Boltzmann thermal
RTM) port, vs. reference values generated by calling
SCOPEinR::get.RTMt.sb with matching inputs -- see
python/scratch/scratch_rtmt_sb_export.R. Only the core (non-``obsdir``,
"SCOPE-lite" scalar-per-layer) branch is ported, see rtmt_sb.py's module
docstring.
"""
from pathlib import Path

import numpy as np
import pandas as pd

from scopeinpython import (
    CanopyStructure,
    RTMoResult,
    SoilParams,
    WettingParams,
    get_bsm,
    get_spectra_scope,
    rtmt_sb,
    run_rtmo,
)
from toolsrtm import prospect_d
from toolsrtm.canopy import dladgen

REFDATA = Path(__file__).parent / "refdata"


def test_rtmt_sb_matches_r():
    profile = pd.read_csv(REFDATA / "ref_rtmt_sb_profile.csv")
    net = pd.read_csv(REFDATA / "ref_rtmt_sb_net.csv")
    scalars = pd.read_csv(REFDATA / "ref_rtmt_sb_scalars.csv").iloc[0]
    temps = pd.read_csv(REFDATA / "ref_rtmt_sb_temps.csv")

    spectral = get_spectra_scope()

    N, Cab, Car, Anth, Cbrown, EWT, LMA, alpha = 1.5, 40, 8, 1, 0.0, 0.01, 0.009, 40
    leaf = prospect_d(N=N, Cab=Cab, Car=Car, Anth=Anth, Cbrown=Cbrown, EWT=EWT, LMA=LMA, alpha=alpha)
    refl_1, tran_1 = leaf.refl[:2001], leaf.tran[:2001]

    LAI, hc, leafwidth = 3.0, 2.0, 0.1
    hot = leafwidth / hc
    LIDFa, LIDFb = -0.35, -0.15
    tts, tto, psi = 30.0, 0.0, 0.0
    lidf = dladgen(LIDFa, LIDFb).lidf
    canopy = CanopyStructure(LAI=LAI, lidf=lidf, hot=hot)
    nl = canopy.nlayers

    rsoil = get_bsm(
        SoilParams(BSMBrightness=0.5, BSMlat=25, BSMlon=45),
        WettingParams(SMp=15, SMC=25, film=0.015),
    )
    rtmo_ref = pd.read_csv(REFDATA / "ref_RTMo_outputs.csv")
    Esun_ = rtmo_ref["Esun_"].to_numpy()
    Esky_ = rtmo_ref["Esky_"].to_numpy()

    rtmo_res: RTMoResult = run_rtmo(
        spectral=spectral, leaf_refl=refl_1, leaf_tran=tran_1,
        rho_thermal=0.01, tau_thermal=0.01, rsoil=rsoil, canopy=canopy,
        tts=tts, tto=tto, psi=psi, Esun_=Esun_, Esky_=Esky_,
    )

    res = rtmt_sb(
        rtmo=rtmo_res, nl=nl, LAI=LAI, rho_thermal=0.01, tau_thermal=0.01, rs_thermal=0.06,
        Tcu=temps["Tcu"].to_numpy(), Tch=temps["Tch"].to_numpy(),
        Tsu=float(scalars["Tsu"]), Tsh=float(scalars["Tsh"]),
    )

    np.testing.assert_allclose(res.Emint, profile["Emint"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.Eplut, profile["Eplut"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.Rnuct, net["Rnuct"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.Rnhct, net["Rnhct"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.Eoutte, scalars["Eoutte"], rtol=1e-6)
    np.testing.assert_allclose(res.Rnust, scalars["Rnust"], rtol=1e-6)
    np.testing.assert_allclose(res.Rnhst, scalars["Rnhst"], rtol=1e-6)
