"""Numerical regression tests for the leaf biochemistry port
(Farquhar/Collatz photosynthesis + van der Tol et al. 2014 fluorescence
yield), vs. reference values generated by running the original R SCOPEinR
package (see python/scratch/scratch_export.R).

Covers both the C3 (iterative Ball-Berry Ci via Brent root-finding,
temperature-corrected) and C4 (closed-form Ci, temperature-corrected)
paths. Note: C4 with temp_correction=False crashes in R itself (a real
bug -- Vcmax/Rd are never assigned in that branch combination, see
biochemical.py's module docstring) so it isn't exercised here.
"""
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from scopeinpython import LeafBio, MeteoLeaf, get_biochemical

REFDATA = Path(__file__).parent / "refdata"

_TDP = dict(delHaV=65330, delSV=485, delHdV=149250, delHaJ=43540, delSJ=495, delHdJ=152040,
            delHaP=53100, delSP=490, delHdP=150650, delHaR=46390, delSR=490, delHdR=150650,
            delHaKc=79430, delHaKo=36380, delHaT=37830,
            Q10=2, s1=0.3, s2=313.15, s3=0.2, s4=288.15, s5=1.3, s6=328.15)

_METEO = MeteoLeaf(Q=800, Cs=400, Temp=25, eb=15, Oa=209, p=1013)

_FIELDS = ["A", "Ci", "rcw", "gs", "RH", "Vcmax", "Rd", "Ja", "ps", "ps_rel", "Kd", "Kn", "NPQ",
           "Kp", "eta", "qE", "fs", "SIF", "fo0", "fm0", "fo", "fm", "qQ", "Phi_N"]


def test_biochemical_c3_matches_r():
    ref = pd.read_csv(REFDATA / "ref_biochemical_c3.csv").iloc[0]
    leafbio = LeafBio(Type="C3", stressfactor=1, Vcmax25=60, BallBerry0=0.01, BallBerrySlope=9,
                       Rdparam=0.015, Kn0=2.48, Knalpha=2.83, Knbeta=0.114, TDP=_TDP)
    res = get_biochemical(leafbio, _METEO, temp_correction=True, fV=1.0)
    for f in _FIELDS:
        py = float(np.atleast_1d(getattr(res, f)).flatten()[0])
        assert py == pytest.approx(ref[f], rel=1e-6, abs=1e-9), f"field {f} mismatch"


def test_biochemical_c4_matches_r():
    ref = pd.read_csv(REFDATA / "ref_biochemical_c4.csv").iloc[0]
    leafbio = LeafBio(Type="C4", stressfactor=1, Vcmax25=30, BallBerry0=0, BallBerrySlope=4,
                       Rdparam=0.025, Kn0=2.48, Knalpha=2.83, Knbeta=0.114, TDP=_TDP)
    res = get_biochemical(leafbio, _METEO, temp_correction=True, fV=1.0)
    for f in _FIELDS:
        py = float(np.atleast_1d(getattr(res, f)).flatten()[0])
        assert py == pytest.approx(ref[f], rel=1e-6, abs=1e-9), f"field {f} mismatch"
