"""Numerical regression test for the RTMo optical BRDF pipeline port, vs.
reference values generated by calling SCOPEinR:::getRTMo directly in R
with matching inputs (leaf optics from PROSPECT-D, soil from BSM) -- see
python/scratch/scratch_rtmo_export.R in the repo root.
"""
from pathlib import Path

import numpy as np
import pandas as pd

from scopeinpython import CanopyStructure, get_spectra_scope, run_rtmo
from toolsrtm.canopy import dladgen

REFDATA = Path(__file__).parent / "refdata"


def test_rtmo_matches_r():
    spectral_in = pd.read_csv(REFDATA / "ref_RTMo_inputs_spectral.csv")
    outputs = pd.read_csv(REFDATA / "ref_RTMo_outputs.csv")
    scalars = pd.read_csv(REFDATA / "ref_RTMo_scalars.csv").iloc[0]
    gap = pd.read_csv(REFDATA / "ref_RTMo_gap.csv")

    leaf_refl = spectral_in["refl_leaf"].to_numpy()
    leaf_tran = spectral_in["tran_leaf"].to_numpy()
    rsoil = spectral_in["rsoil"].to_numpy()

    lidf = dladgen(scalars["LIDFa"], scalars["LIDFb"]).lidf

    canopy = CanopyStructure(
        LAI=scalars["LAI"], lidf=lidf, hot=scalars["hot"], nlayers=int(scalars["nl"]),
    )

    spectral = get_spectra_scope()

    Esun_ = outputs["Esun_"].to_numpy()
    Esky_ = outputs["Esky_"].to_numpy()

    result = run_rtmo(
        spectral=spectral,
        leaf_refl=leaf_refl, leaf_tran=leaf_tran,
        rho_thermal=0.01, tau_thermal=0.01,
        rsoil=rsoil,
        canopy=canopy,
        tts=scalars["tts"], tto=scalars["tto"], psi=scalars["psi"],
        Esun_=Esun_, Esky_=Esky_,
    )

    np.testing.assert_allclose(result.k, scalars["k"], rtol=1e-8)
    np.testing.assert_allclose(result.K, scalars["K"], rtol=1e-8)

    np.testing.assert_allclose(result.rdd, outputs["rdd"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(result.rsd, outputs["rsd"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(result.rdo, outputs["rdo"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(result.rso, outputs["rso"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(result.refl, outputs["refl"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(result.Lo_, outputs["Lo_"].to_numpy(), rtol=1e-5, atol=1e-6)
    np.testing.assert_allclose(result.Eout_, outputs["Eout_"].to_numpy(), rtol=1e-5, atol=1e-6)

    np.testing.assert_allclose(result.Ps, gap["Ps"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(result.Po, gap["Po"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(result.Pso, gap["Pso"].to_numpy(), rtol=1e-4, atol=1e-8)
