"""Numerical regression test for the RTMz zeaxanthin RTM port, vs.
reference values generated by calling SCOPEinR::get.RTMz (the fixed R
source, see rtmz.py's module docstring) with matching inputs -- see
python/scratch/scratch_rtmz_export.R.

No spline-interpolation approximation is involved here (unlike RTMf) --
RTMz works entirely on the native 500-600nm grid -- so this is checked to
the same tight tolerance as the rest of this port.
"""
from pathlib import Path

import numpy as np
import pandas as pd

from scopeinpython import (
    CanopyStructure,
    LeafBio,
    MeteoLeaf,
    MultiLayerLeafBio,
    RTMoResult,
    SoilParams,
    WettingParams,
    fluspect_mscope,
    get_biochemical,
    get_bsm,
    get_spectra_scope,
    run_rtmo,
    rtmz,
)
from toolsrtm import prospect_d
from toolsrtm.canopy import dladgen

REFDATA = Path(__file__).parent / "refdata"


def test_rtmz_matches_r():
    ref = pd.read_csv(REFDATA / "ref_rtmz.csv")

    spectral = get_spectra_scope()

    N, Cab, Car, Anth, Cbrown, EWT, LMA, alpha = 1.5, 40, 8, 1, 0.0, 0.01, 0.009, 40
    leaf = prospect_d(N=N, Cab=Cab, Car=Car, Anth=Anth, Cbrown=Cbrown, EWT=EWT, LMA=LMA, alpha=alpha)
    refl_1, tran_1 = leaf.refl[:2001], leaf.tran[:2001]

    LAI, hc, leafwidth = 3.0, 2.0, 0.1
    hot = leafwidth / hc
    LIDFa, LIDFb = -0.35, -0.15
    tts, tto, psi = 30.0, 0.0, 0.0
    lidf = dladgen(LIDFa, LIDFb).lidf
    canopy = CanopyStructure(LAI=LAI, lidf=lidf, hot=hot)
    nl = canopy.nlayers

    rsoil = get_bsm(
        SoilParams(BSMBrightness=0.5, BSMlat=25, BSMlon=45),
        WettingParams(SMp=15, SMC=25, film=0.015),
    )

    rtmo_ref = pd.read_csv(REFDATA / "ref_RTMo_outputs.csv")
    Esun_ = rtmo_ref["Esun_"].to_numpy()
    Esky_ = rtmo_ref["Esky_"].to_numpy()

    rtmo_res: RTMoResult = run_rtmo(
        spectral=spectral, leaf_refl=refl_1, leaf_tran=tran_1,
        rho_thermal=0.01, tau_thermal=0.01, rsoil=rsoil, canopy=canopy,
        tts=tts, tto=tto, psi=psi, Esun_=Esun_, Esky_=Esky_,
    )

    mly = MultiLayerLeafBio(
        nly=1, pLAI=np.array([1.0]), pCab=np.array([Cab]), pEWT=np.array([EWT]),
        pCar=np.array([Car]), pLMA=np.array([LMA]), pCs=np.array([0.0]), pN=np.array([N]),
    )
    leafopt0 = fluspect_mscope(mly=mly, spectral=spectral, nl=nl, Cx=0, fqe=0.01, Prot=0.001, CBC=0.008, Anth=1, step=5)
    leafopt1 = fluspect_mscope(mly=mly, spectral=spectral, nl=nl, Cx=1, fqe=0.01, Prot=0.001, CBC=0.008, Anth=1, step=5)

    TDP = dict(delHaV=65330, delSV=485, delHdV=149250, delHaJ=43540, delSJ=495, delHdJ=152040,
               delHaP=53100, delSP=490, delHdP=150650, delHaR=46390, delSR=490, delHdR=150650,
               delHaKc=79430, delHaKo=36380, delHaT=37830,
               Q10=2, s1=0.3, s2=313.15, s3=0.2, s4=288.15, s5=1.3, s6=328.15)
    bio = get_biochemical(
        LeafBio(Type="C3", stressfactor=1, Vcmax25=60, BallBerry0=0.01, BallBerrySlope=9,
                Rdparam=0.015, Kn0=2.48, Knalpha=2.83, Knbeta=0.114, TDP=TDP),
        MeteoLeaf(Q=800, Cs=400, Temp=25, eb=15, Oa=209, p=1013),
        temp_correction=True, fV=1.0,
    )
    Kn_val = float(np.atleast_1d(bio.Kn).flatten()[0])
    Knu = np.full((nl, 13, 36), Kn_val)
    Knh = np.full(nl, Kn_val)

    res = rtmz(
        spectral=spectral, rtmo=rtmo_res, canopy=canopy, tts=tts, tto=tto, psi=psi,
        rsoil=rsoil, refl=leafopt0.refl, tran=leafopt0.tran,
        reflZ=leafopt1.refl, tranZ=leafopt1.tran, Knu=Knu, Knh=Knh,
    )

    rso_after_py = rtmo_res.rso[100:201] + res.rso_delta
    rdo_after_py = rtmo_res.rdo[100:201] + res.rdo_delta
    Eout_after_py = rtmo_res.Eout_[100:201] + res.Eout_delta

    np.testing.assert_allclose(rso_after_py, ref["rso_after"].to_numpy(), rtol=1e-5, atol=1e-9)
    np.testing.assert_allclose(rdo_after_py, ref["rdo_after"].to_numpy(), rtol=1e-5, atol=1e-9)
    np.testing.assert_allclose(Eout_after_py, ref["Eout_after"].to_numpy(), rtol=1e-4, atol=1e-6)

    # sanity: the correction is genuinely non-zero somewhere (regression
    # against the get.plots-only-output bug silently no-op'ing)
    assert np.max(np.abs(res.rso_delta)) > 1e-4
