"""Numerical regression tests for the SCOPE-variant FLUSPECT-B-Cx port
(``getFluspect.Cx.SCOPE``), vs. reference values generated by running the
original R SCOPEinR package (see python/scratch/scratch_export.R).

Covers both step=5 (SCOPE's own default, 53x71 Mb/Mf matrices -- this is
what ``fluspect_mSCOPE.R``/RTMf actually use) and step=1 (211x351,
structurally similar to toolsrtm.fluspect_cx but NOT numerically identical
to it -- see fluspect.py's module docstring for why these are genuinely
different functions despite similar code).
"""
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from scopeinpython import get_fluspect_cx_scope

REFDATA = Path(__file__).parent / "refdata"

_LUT = dict(Cab=40, Car=10, EWT=0.015, LMA=0.01, Cs=0.1, N=1.8, fqe=0.01, Cx=0.5,
            Prot=0.001, CBC=0.008, Anth=1)


@pytest.mark.parametrize("step,shape", [(5, (53, 71)), (1, (211, 351))])
def test_fluspect_cx_scope_matches_r(step, shape):
    label = f"step{step}"
    ref = pd.read_csv(REFDATA / f"ref_fluspect_scope_{label}_refltran.csv")
    ref_Mb = pd.read_csv(REFDATA / f"ref_fluspect_scope_{label}_Mb.csv").to_numpy()
    ref_Mf = pd.read_csv(REFDATA / f"ref_fluspect_scope_{label}_Mf.csv").to_numpy()

    res = get_fluspect_cx_scope(step=step, **_LUT)

    assert res.Mb.shape == shape
    np.testing.assert_allclose(res.refl, ref["refl"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.tran, ref["tran"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.kChlrel, ref["kChlrel"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.kCarrel, ref["kCarrel"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.Mb, ref_Mb, rtol=1e-6, atol=1e-12)
    np.testing.assert_allclose(res.Mf, ref_Mf, rtol=1e-6, atol=1e-12)


def test_fluspect_cx_scope_returns_none_for_zero_fqe():
    lut = {**_LUT, "fqe": 0.0}
    assert get_fluspect_cx_scope(**lut) is None
