"""Numerical regression test for net_radiation_lite (rtmo.py's partial
section-4 port), vs. reference values generated by calling
SCOPEinR:::getRTMo (the fixed R source -- see python/scratch/scratch_netrad_export.R
and rtmo.py's module docstring for the direct-beam-term bug found and
fixed here).

Note: this test's leaf optics have kChlrel=0 (plain PROSPECT-D, no
Fluspect leaf model), so Pnu_Cab/Pnh_Cab both come out exactly zero in R
and Python alike -- this exercises the code path (no crash, right shape)
but not the numeric kChlrel-weighting itself.
"""
from pathlib import Path

import numpy as np
import pandas as pd

from scopeinpython import CanopyStructure, get_bsm, get_spectra_scope, net_radiation_lite, run_rtmo, SoilParams, WettingParams
from toolsrtm import prospect_d
from toolsrtm.canopy import dladgen

REFDATA = Path(__file__).parent / "refdata"


def test_net_radiation_lite_matches_r():
    layers = pd.read_csv(REFDATA / "ref_netrad_layers.csv")
    soil = pd.read_csv(REFDATA / "ref_netrad_soil.csv").iloc[0]

    spectral = get_spectra_scope()

    N, Cab, Car, Anth, Cbrown, EWT, LMA, alpha = 1.5, 40, 8, 1, 0.0, 0.01, 0.009, 40
    leaf = prospect_d(N=N, Cab=Cab, Car=Car, Anth=Anth, Cbrown=Cbrown, EWT=EWT, LMA=LMA, alpha=alpha)
    refl_1, tran_1 = leaf.refl[:2001], leaf.tran[:2001]

    LAI, hc, leafwidth = 3.0, 2.0, 0.1
    hot = leafwidth / hc
    LIDFa, LIDFb = -0.35, -0.15
    tts, tto, psi = 30.0, 0.0, 0.0
    lidf = dladgen(LIDFa, LIDFb).lidf
    lazitab = np.arange(5, 356, 10).astype(float)
    canopy = CanopyStructure(LAI=LAI, lidf=lidf, hot=hot)
    nl = canopy.nlayers

    rsoil = get_bsm(
        SoilParams(BSMBrightness=0.5, BSMlat=25, BSMlon=45),
        WettingParams(SMp=15, SMC=25, film=0.015),
    )
    rtmo_ref = pd.read_csv(REFDATA / "ref_RTMo_outputs.csv")
    Esun_ = rtmo_ref["Esun_"].to_numpy()
    Esky_ = rtmo_ref["Esky_"].to_numpy()

    rtmo_res = run_rtmo(
        spectral=spectral, leaf_refl=refl_1, leaf_tran=tran_1,
        rho_thermal=0.01, tau_thermal=0.01, rsoil=rsoil, canopy=canopy,
        tts=tts, tto=tto, psi=psi, Esun_=Esun_, Esky_=Esky_,
    )

    kChlrel = np.zeros(2001)  # matches the R reference's plain-PROSPECT-D leaf optics

    res = net_radiation_lite(
        spectral=spectral, rtmo=rtmo_res, canopy=canopy, tts=tts, lazitab=lazitab,
        leaf_refl=refl_1, leaf_tran=tran_1, rho_thermal=0.01, tau_thermal=0.01,
        rsoil=rsoil, kChlrel=kChlrel,
    )

    np.testing.assert_allclose(res.Rnuc, layers["Rnuc"].to_numpy(), rtol=1e-5, atol=1e-6)
    np.testing.assert_allclose(res.Rnhc, layers["Rnhc"].to_numpy(), rtol=1e-5, atol=1e-6)
    np.testing.assert_allclose(res.Pnu_Cab, layers["Pnu_Cab"].to_numpy(), atol=1e-9)
    np.testing.assert_allclose(res.Pnh_Cab, layers["Pnh_Cab"].to_numpy(), atol=1e-9)
    np.testing.assert_allclose(res.Rnus, soil["Rnus"], rtol=1e-5)
    np.testing.assert_allclose(res.Rnhs, soil["Rnhs"], rtol=1e-5)
