"""Numerical regression test for the mSCOPE multi-layer leaf-optics wrapper
(``get.fluspect_mSCOPE``), vs. reference values generated by running the
original R SCOPEinR package (see python/scratch/scratch_export.R, section 15).

Also exercises the profile-layer-boundary overwrite quirk reproduced from
R (see fluspect_mscope.py's module docstring): this is implicitly covered
since the reference case's ``pLAI``/``nl`` combination produces boundary
rows shared between profile layers, and the test compares the full
(nl, nwlP) array, not just spot values.
"""
from pathlib import Path

import numpy as np
import pandas as pd

from scopeinpython import MultiLayerLeafBio, fluspect_mscope, get_spectra_scope

REFDATA = Path(__file__).parent / "refdata"

_MLY = MultiLayerLeafBio(
    nly=3,
    pLAI=np.array([0.5, 1.0, 0.5]),
    pCab=np.array([50.0, 35.0, 20.0]),
    pEWT=np.array([0.02, 0.015, 0.01]),
    pCar=np.array([12.0, 9.0, 6.0]),
    pLMA=np.array([0.012, 0.01, 0.008]),
    pCs=np.array([0.05, 0.1, 0.15]),
    pN=np.array([2.0, 1.8, 1.5]),
)
_NL = 10


def test_fluspect_mscope_matches_r():
    spectral = get_spectra_scope()
    res = fluspect_mscope(
        mly=_MLY, spectral=spectral, nl=_NL,
        Cx=0.5, fqe=0.01, Prot=0.001, CBC=0.008, Anth=1, step=5,
    )

    ref_refl = pd.read_csv(REFDATA / "ref_fluspect_mscope_refl.csv").to_numpy()
    ref_tran = pd.read_csv(REFDATA / "ref_fluspect_mscope_tran.csv").to_numpy()
    ref_kChlrel = pd.read_csv(REFDATA / "ref_fluspect_mscope_kChlrel.csv").to_numpy()
    ref_kCarrel = pd.read_csv(REFDATA / "ref_fluspect_mscope_kCarrel.csv").to_numpy()
    ref_phi = pd.read_csv(REFDATA / "ref_fluspect_mscope_phi.csv")

    assert res.refl.shape == (_NL, 2001)
    np.testing.assert_allclose(res.refl, ref_refl, rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.tran, ref_tran, rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.kChlrel, ref_kChlrel, rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.kCarrel, ref_kCarrel, rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.phiI, ref_phi["phiI"].to_numpy(), rtol=1e-6, atol=1e-12)
    np.testing.assert_allclose(res.phiII, ref_phi["phiII"].to_numpy(), rtol=1e-6, atol=1e-12)

    assert res.Mb.shape == (53, 71, _NL)
    ref_Mb = pd.read_csv(REFDATA / "ref_fluspect_mscope_Mb.csv").to_numpy()
    ref_Mf = pd.read_csv(REFDATA / "ref_fluspect_mscope_Mf.csv").to_numpy()
    for layer in range(_NL):
        np.testing.assert_allclose(
            res.Mb[:, :, layer], ref_Mb[:, layer].reshape(53, 71, order="F"),
            rtol=1e-6, atol=1e-12,
        )
        np.testing.assert_allclose(
            res.Mf[:, :, layer], ref_Mf[:, layer].reshape(53, 71, order="F"),
            rtol=1e-6, atol=1e-12,
        )
