"""Numerical regression test for the get_scope() end-to-end wrapper (task
6), vs. reference values generated by calling the REAL, unmodified
SCOPEinR::get.SCOPE() against its own bundled example LUT_input.csv /
setoptions.csv (the fixed R source -- RTMo.R/RTMf.R/RTMz.R bugs fixed
earlier this session) -- see python/scratch/scratch_scope_export.R.
"""
import csv
from pathlib import Path

import numpy as np
import pandas as pd

from scopeinpython import ScopeOptions, get_scope

REFDATA = Path(__file__).parent / "refdata"
LUT_CSV = Path(__file__).parents[3] / "SCOPEinR" / "inst" / "input" / "LUT_input.csv"


def _lut_row() -> dict:
    with open(LUT_CSV, newline="") as f:
        return next(csv.DictReader(f))


def test_get_scope_matches_r():
    row = _lut_row()
    res = get_scope(row, options=ScopeOptions(k_maxit=100, maxEBer=1.0))

    scalars = pd.read_csv(REFDATA / "ref_scope_scalars.csv").iloc[0]
    temps = pd.read_csv(REFDATA / "ref_scope_temps.csv")
    spectral_ref = pd.read_csv(REFDATA / "ref_scope_spectral.csv")

    assert res.nlayers == int(scalars["nlayers"])

    # Exact-formula quantities (no iterative-convergence path involved):
    # match R to floating-point noise.
    np.testing.assert_allclose(res.LAIsunlit, scalars["LAIsunlit"], rtol=1e-10)
    np.testing.assert_allclose(res.LAIshaded, scalars["LAIshaded"], rtol=1e-10)
    np.testing.assert_allclose(res.Pnsun_Cab, scalars["Pnsun_Cab"], rtol=1e-10)
    np.testing.assert_allclose(res.Pnsha_Cab, scalars["Pnsha_Cab"], rtol=1e-10)
    np.testing.assert_allclose(res.Pntot_Cab, scalars["Pntot_Cab"], rtol=1e-10)

    # TOC optical BRDF spectrum: also no iterative-convergence path.
    refl = res.rtmo.refl
    refl_ref = spectral_ref["refl"].to_numpy()
    finite = np.isfinite(refl_ref)  # far-thermal rso/refl legitimately NaN, see rtmo.py
    np.testing.assert_allclose(refl[finite], refl_ref[finite], rtol=1e-9)

    # ebal-derived quantities: small floating-point divergence expected from
    # the per-layer-loop biochemistry path over ~7-10 nonlinear iterations
    # (matches test_ebal.py's own tolerance for the same reason).
    np.testing.assert_allclose(res.ebal.Tcu, temps["Tcu"].to_numpy(), rtol=1e-3, atol=1e-2)
    np.testing.assert_allclose(res.ebal.Tch, temps["Tch"].to_numpy(), rtol=1e-3, atol=1e-2)
    np.testing.assert_allclose(res.ebal.Tcave, scalars["Tcave"], rtol=1e-3)
    np.testing.assert_allclose(res.ebal.canopyemis, scalars["canopyemis"], rtol=1e-3)
    for field in ["Rnctot", "lEctot", "Hctot", "Actot", "Rnstot", "lEstot", "Hstot", "Gtot", "Rntot", "lEtot", "Htot"]:
        np.testing.assert_allclose(getattr(res.ebal, field), scalars[field], rtol=2e-2)
    np.testing.assert_allclose(res.Ja, scalars["Ja"], rtol=2e-2)
    np.testing.assert_allclose(res.PNPQ, scalars["PNPQ"], rtol=2e-2)
    np.testing.assert_allclose(res.fqe, scalars["fqe"], rtol=5e-2)

    assert res.rtmf is not None
    np.testing.assert_allclose(res.rtmf.EoutF, scalars["EoutF"], rtol=2e-2)

    assert res.rtmz is not None
    assert res.rtmz.LoF_.shape == (101, 2)


def test_get_scope_options_disable_fluor_and_xanthophyll():
    row = _lut_row()
    res = get_scope(row, options=ScopeOptions(calc_fluor=False, calc_xanthophyllabs=False))
    assert res.rtmf is None
    assert res.rtmz is None
    assert res.fqe is None
