"""Numerical regression test for the RTMf fluorescence RTM port, vs.
reference values generated by calling SCOPEinR::get.RTMf (the fixed R
source, see rtmf.py's module docstring) with matching inputs -- see
python/scratch/scratch_rtmf_export.R.

Two tiers of comparison, matching how the reference was captured:

- ``ref_rtmf_native.csv``: the native 640-850nm (4nm step, 53pt) pre-spline
  quantities (piLo1..4, LoF_native, Fhem_native) -- these involve none of
  the spline-interpolation approximation documented in rtmf.py, so are
  checked to the same tight tolerance as the rest of this port.
- ``ref_rtmf_interp.csv``/``ref_rtmf_scalars.csv``: the normal, fully
  interpolated get.RTMf() output on the 211-pt spectral.wlF grid -- checked
  with a looser tolerance reflecting the documented not-a-knot-vs-fmm
  spline approximation (worst case observed ~1.5e-3 absolute, localized
  near the two ends of the native grid).
"""
from pathlib import Path

import numpy as np
import pandas as pd

from scopeinpython import (
    CanopyStructure,
    MultiLayerLeafBio,
    RTMoResult,
    fluspect_mscope,
    get_bsm,
    get_spectra_scope,
    rtmf,
    run_rtmo,
    LeafBio,
    MeteoLeaf,
    SoilParams,
    WettingParams,
    get_biochemical,
)
from toolsrtm.canopy import dladgen
from toolsrtm import prospect_d

REFDATA = Path(__file__).parent / "refdata"


def test_rtmf_matches_r():
    native = pd.read_csv(REFDATA / "ref_rtmf_native.csv")
    interp = pd.read_csv(REFDATA / "ref_rtmf_interp.csv")
    scalars = pd.read_csv(REFDATA / "ref_rtmf_scalars.csv").iloc[0]

    spectral = get_spectra_scope()

    N, Cab, Car, Anth, Cbrown, EWT, LMA, alpha = 1.5, 40, 8, 1, 0.0, 0.01, 0.009, 40
    leaf = prospect_d(N=N, Cab=Cab, Car=Car, Anth=Anth, Cbrown=Cbrown, EWT=EWT, LMA=LMA, alpha=alpha)
    refl_1, tran_1 = leaf.refl[:2001], leaf.tran[:2001]

    LAI, hc, leafwidth = 3.0, 2.0, 0.1
    hot = leafwidth / hc
    LIDFa, LIDFb = -0.35, -0.15
    tts, tto, psi = 30.0, 0.0, 0.0
    lidf = dladgen(LIDFa, LIDFb).lidf
    canopy = CanopyStructure(LAI=LAI, lidf=lidf, hot=hot)
    nl = canopy.nlayers

    rsoil = get_bsm(
        SoilParams(BSMBrightness=0.5, BSMlat=25, BSMlon=45),
        WettingParams(SMp=15, SMC=25, film=0.015),
    )

    Esun_ = np.zeros(len(spectral.wlS))
    Esky_ = np.zeros(len(spectral.wlS))
    # Reuse the same default SCOPEinR irradiance bundled for the RTMo test.
    rtmo_ref = pd.read_csv(REFDATA / "ref_RTMo_outputs.csv")
    Esun_ = rtmo_ref["Esun_"].to_numpy()
    Esky_ = rtmo_ref["Esky_"].to_numpy()

    rtmo_res: RTMoResult = run_rtmo(
        spectral=spectral, leaf_refl=refl_1, leaf_tran=tran_1,
        rho_thermal=0.01, tau_thermal=0.01, rsoil=rsoil, canopy=canopy,
        tts=tts, tto=tto, psi=psi, Esun_=Esun_, Esky_=Esky_,
    )

    mly = MultiLayerLeafBio(
        nly=1, pLAI=np.array([1.0]), pCab=np.array([Cab]), pEWT=np.array([EWT]),
        pCar=np.array([Car]), pLMA=np.array([LMA]), pCs=np.array([0.0]), pN=np.array([N]),
    )
    leafopt = fluspect_mscope(
        mly=mly, spectral=spectral, nl=nl, Cx=0.5, fqe=0.01, Prot=0.001, CBC=0.008, Anth=1, step=5,
    )

    TDP = dict(delHaV=65330, delSV=485, delHdV=149250, delHaJ=43540, delSJ=495, delHdJ=152040,
               delHaP=53100, delSP=490, delHdP=150650, delHaR=46390, delSR=490, delHdR=150650,
               delHaKc=79430, delHaKo=36380, delHaT=37830,
               Q10=2, s1=0.3, s2=313.15, s3=0.2, s4=288.15, s5=1.3, s6=328.15)
    bio = get_biochemical(
        LeafBio(Type="C3", stressfactor=1, Vcmax25=60, BallBerry0=0.01, BallBerrySlope=9,
                Rdparam=0.015, Kn0=2.48, Knalpha=2.83, Knbeta=0.114, TDP=TDP),
        MeteoLeaf(Q=800, Cs=400, Temp=25, eb=15, Oa=209, p=1013),
        temp_correction=True, fV=1.0,
    )
    eta_val = float(np.atleast_1d(bio.eta).flatten()[0])
    etau = np.full((nl, 13, 36), eta_val)
    etah = np.full(nl, eta_val)

    res = rtmf(
        spectral=spectral, rtmo=rtmo_res, canopy=canopy, tts=tts, tto=tto, psi=psi,
        rsoil=rsoil, Mb=leafopt.Mb, Mf=leafopt.Mf, etau=etau, etah=etah,
    )

    # -- at the exact native-grid wavelengths (640, 644, ..., 848), CubicSpline
    # reproduces its input data exactly by construction (interpolation, not
    # smoothing) -- so this is effectively a tight-tolerance check on the
    # pre-spline physics (piLo1..4/LoF_native), independent of the spline
    # approximation documented in rtmf.py.
    native_idx = [int(w) - int(spectral.wlF[0]) for w in native["wlF_native"] if w <= spectral.wlF[-1]]
    n_native_valid = len(native_idx)
    np.testing.assert_allclose(
        res.LoF_[native_idx], native["LoF_native"].to_numpy()[:n_native_valid], rtol=1e-6, atol=1e-9
    )

    # -- fully interpolated output: looser tolerance (documented spline approximation) --
    np.testing.assert_allclose(res.LoF_, interp["LoF_"].to_numpy(), rtol=1e-2, atol=2e-3)
    np.testing.assert_allclose(res.EoutF_, interp["EoutF_"].to_numpy(), rtol=1e-2, atol=2e-3)

    np.testing.assert_allclose(res.EoutF, scalars["EoutF"], rtol=1e-3)
    np.testing.assert_allclose(res.LoutF, scalars["LoutF"], rtol=1e-3)
    np.testing.assert_allclose(res.F740, scalars["F740"], rtol=1e-2)
    assert np.isnan(res.F685) == np.isnan(scalars["F685"])
