"""Numerical regression test for the BSM soil model port vs. reference
values generated by running the original R SCOPEinR package (see
python/scratch/scratch_export.R)."""
from pathlib import Path

import numpy as np
import pandas as pd

from scopeinpython import SoilParams, WettingParams, get_bsm

REFDATA = Path(__file__).parent / "refdata"


def test_bsm_matches_r():
    ref = pd.read_csv(REFDATA / "ref_BSM.csv")

    soilpar = SoilParams(BSMBrightness=0.5, BSMlat=25, BSMlon=45)
    emp = WettingParams(SMp=15, SMC=25, film=0.015)

    rwet = get_bsm(soilpar, emp)

    np.testing.assert_allclose(rwet, ref["rwet"].to_numpy(), rtol=1e-8, atol=1e-10)
